import Head from 'next/head'
import {  Azeret_Mono  } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const azeret = Azeret_Mono({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
        <Head>
          <title>connect-metamask</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={`${styles.main} ${azeret.className}`}>
          <p>connecting metamask 🦊 using next.js and ethers.js</p>
          <button className={`${styles.btn} ${azeret.className}`}>connect</button>
        </main>
    </>
  )
}