import Head from 'next/head'
import {  Azeret_Mono  } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { ethers } from 'ethers' //got an error for lastest version, fixed it using npm i -S ethers@5.7.2
import { useEffect, useState } from 'react'

const azeret = Azeret_Mono({ subsets: ['latin'] })

export default function Home() {
  // to use ether.js we need a provider, a signer and a contract
  const [walletAddress, setWalletAddress] = useState('')
  const [isConnected, setIsConnected] = useState(false)
  const [signer, setSigner] = useState(undefined)

  async function connect() {
    if(typeof window.ethereum !== 'undefined') {
      try {
        const accounts = await ethereum.request({ method: "eth_requestAccounts" })
        setWalletAddress(accounts[0]);

        setIsConnected(true)
        const provider = new ethers.providers.Web3Provider(window.ethereum)
        setSigner(provider.getSigner())
      } catch(e) {
        console.log(e)
      }
    }
    else {
      setIsConnected(false)
    }
  }

  return (
    <>
        <Head>
          <title>connect-metamask</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={`${styles.main} ${azeret.className}`}>
          <p>connecting wallet using next.js and ethers.js</p>
          {
            isConnected ? `connected: ${walletAddress} ` : <button className={`${styles.btn} ${azeret.className}`} onClick={() => connect()}>connect</button> //fix case sensibility
          }
          
        </main>
    </>
  )
}